DECLARE @N1 INT, @N2 INT, @N3 INT;
DECLARE @MAI_MARE INT;
SET @N1 = 60 * RAND();
SET @N2 = 60 * RAND();
SET @N3 = 60 * RAND();

SET @MAI_MARE = @N1
SET @MAI_MARE = CASE   
    WHEN @N2 > @MAI_MARE THEN @N2
	ELSE @MAI_MARE
END;
SET @MAI_MARE = CASE   
    WHEN @N3 > @MAI_MARE THEN @N3
	ELSE @MAI_MARE
END;

PRINT @N1;
PRINT @N2;
PRINT @N3;
PRINT 'Mai mare = ' + CAST(@MAI_MARE AS VARCHAR(2));