Use universitatea
Go

DROP FUNCTION IF EXISTS PERSON_AGE;
Go

CREATE FUNCTION PERSON_AGE(@DATE DATE = NULL)
RETURNS INT
AS
BEGIN
DECLARE @CURRENT_DATE DATE = GETDATE();
DECLARE @ANS INT = YEAR(@CURRENT_DATE) - YEAR(@DATE);
IF MONTH(@CURRENT_DATE) < MONTH(@DATE) OR  (MONTH(@CURRENT_DATE) = MONTH(@DATE) AND DAY(@CURRENT_DATE) < DAY(@DATE))
SET @ANS = @ANS - 1;
RETURN @ANS;
END; 
