Use universitatea
Go

DROP PROCEDURE IF EXISTS ALT_PROFESOR;
Go

CREATE PROCEDURE ALT_PROFESOR
	@NUME_PROFESOR_VECHI VARCHAR(60),
	@PRENUME_PROFESOR_VECHI VARCHAR(60),
	@NUME_PROFESOR_NOU VARCHAR(60),
	@PRENUME_PROFESOR_NOU VARCHAR(60),
	@DISCIPLINA VARCHAR(255)
AS
	BEGIN
	BEGIN TRY
		
		DECLARE @OLD_PROFESOR_ID INT = (SELECT p.Id_Profesor
				FROM profesori AS p
				WHERE p.Nume_Profesor = @NUME_PROFESOR_VECHI AND p.Prenume_Profesor = @PRENUME_PROFESOR_VECHI);
		
		DECLARE @NEW_PROFESOR_ID INT = (SELECT p.Id_Profesor
				FROM profesori AS p
				WHERE p.Nume_Profesor = @NUME_PROFESOR_NOU AND p.Prenume_Profesor = @PRENUME_PROFESOR_NOU);

		DECLARE @DISCIPLINA_ID INT = (SELECT d.Id_Disciplina
				FROM discipline AS d
				WHERE d.Disciplina = @DISCIPLINA);

		IF @OLD_PROFESOR_ID IS NOT NULL AND @NEW_PROFESOR_ID IS NOT NULL AND @DISCIPLINA_ID IS NOT NULL
			BEGIN
				UPDATE studenti_reusita
				SET Id_Profesor = @NEW_PROFESOR_ID
				WHERE Id_Profesor = @OLD_PROFESOR_ID AND Id_Disciplina = @DISCIPLINA_ID
				RETURN;
			END
		RAISERROR ('INVALID INPUT DATA', -- Message text.  
					11, -- Severity.  
					1 -- State.  
					);
	END TRY
	BEGIN CATCH
		SELECT   
        ERROR_NUMBER() AS ErrorNumber  
       ,ERROR_MESSAGE() AS ErrorMessage;
	END CATCH
END;