Use universitatea
Go

DROP PROCEDURE IF EXISTS RESTANTA;
Go

CREATE PROCEDURE RESTANTA
	@RESTANTIERI INT = 0 OUTPUT
AS
	BEGIN
	(SELECT @RESTANTIERI = COUNT(DISTINCT Id_Student)
	FROM studenti_reusita as st_r
	WHERE Nota < 5 or Nota IS NULL)
	END