Use universitatea
Go

DROP PROCEDURE IF EXISTS NEW_STUDENT;
Go

CREATE PROCEDURE NEW_STUDENT
	@ID_STUDENT INT = 100,
	@NUME_STUDENT VARCHAR(50) = 'UNNAMED',
	@PRENUME_STUDENT VARCHAR(50) = 'UNNAMED',
	@DATA_NASTERE_STUDENT DATE = '1997-01-01',
	@ADRESA_POSTALA_STUDENT VARCHAR(500) = 'UNKNOWN',
	@COD_GRUPA VARCHAR(6) = 'FAF161',
	@SPECIALITATE VARCHAR(255) = 'Software Ingeneering',
	@FACULTATE varchar(255) = 'CIM',
	@ID_DISCIPLINA INT = 100,
	@ID_PROFESOR INT = 108,
	@TIP_EVALUARE VARCHAR(60) = 'Examen',
	@ID_GRUPA INT = 1
AS
	BEGIN
	DECLARE @POSSIBLE_ID INT = @ID_STUDENT;
	IF EXISTS (SELECT s.Id_Student
			FROM studenti AS s
			WHERE s.Id_Student = @ID_STUDENT)
	BEGIN
		SET @POSSIBLE_ID = 1 + (SELECT MAX(Id_Student) FROM studenti)
	END;

	INSERT INTO [dbo].[studenti_reusita] (Id_Student, Id_Grupa, Id_Profesor, Id_Disciplina, Tip_Evaluare)
	VALUES (@POSSIBLE_ID, @ID_GRUPA, @ID_PROFESOR, @ID_DISCIPLINA, @TIP_EVALUARE);
	
	END;