DROP TRIGGER IF EXISTS [studenti].[Studenti_StudentiReusita_Insertion]
GO

CREATE TRIGGER Studenti_StudentiReusita_Insertion ON studenti.studenti_reusita
INSTEAD OF INSERT
AS 
	SET NOCOUNT ON
	DECLARE @ID_STUDENT INT;
	DECLARE @NUME_STUDENT VARCHAR(50) = 'UNDEFINED';
	DECLARE @PRENUME_STUDENT VARCHAR(50) = 'UNDEFINED';
	DECLARE @DATA_NASTERE_STUDENT DATE = NULL;
	DECLARE @ADRESA_POSTALA_STUDENT VARCHAR(255) = 'mun. Chisinau';

	SELECT @ID_STUDENT = inserted.Id_Student
	FROM inserted;
	
	INSERT INTO studenti.studenti
	VALUES 
        (@ID_STUDENT, @NUME_STUDENT, @PRENUME_STUDENT, @DATA_NASTERE_STUDENT, @ADRESA_POSTALA_STUDENT);
	
	INSERT INTO studenti.studenti_reusita
	SELECT * 
	FROM inserted;
GO