DROP TRIGGER IF EXISTS ATTRIBUTE_PROTECTOR ON Database
GO

CREATE TRIGGER ATTRIBUTE_PROTECTOR
ON DATABASE
FOR ALTER_TABLE
AS
	DECLARE @COLUMN_NAME VARCHAR(250);
	SELECT @COLUMN_NAME = EVENTDATA().value('(/EVENT_INSTANCE/AlterTableActionList/*/Columns/Name)[1]', 'nvarchar(100)') 
	
	IF @COLUMN_NAME LIKE 'Disciplina'
	BEGIN 
		PRINT ('REJECTED!!! Column ' + @COLUMN_NAME + ' can''t be modified')
		ROLLBACK;
	END
