DROP TRIGGER IF EXISTS SCHEME_PROTECTOR ON DATABASE;
GO

CREATE TRIGGER SCHEME_PROTECTOR
ON DATABASE
FOR ALTER_TABLE
AS
	DECLARE @START INT = 9 * 60 * 60;
	DECLARE @END INT = 20 * 60 * 60;

	DECLARE @DATE DATETIME = GETDATE();
	DECLARE @CURRENT_TIME INT = (DATEPART(HOUR, @DATE) * 60 * 60) +
								(DATEPART(MINUTE, @DATE) * 60) +
								(DATEPART(SECOND, @DATE));
	

	IF @CURRENT_TIME NOT BETWEEN @START AND @END
		BEGIN
		PRINT('RESERVED HOURS!!! MODIFICATIONS HAVE BEEN INVALIDATED!!!')
		ROLLBACK
		END;